<?php
define('ACTION_OK', 1);
define('ACTION_FAILED', 2);
define('SERVER_ERROR', 3);
define('FORM_DATA_MISSING', 4);
define('PASSWORDS_DO_NOT_MATCH', 5);
define('NO_PERMISSION', 6);
define('WORKER_NAME_ALREADY_EXISTS', 7);
define('LOGIN_REQUIRED', 8);
define('NO_LOGIN_REQUIRED', 9);
define('DOCUMENT_NUMBER_ALREADY_EXISTS', 10);
define('CUSTOMER_NUMBER_ALREADY_EXISTS', 11);
?>